# Generated by Django 5.0.1 on 2024-02-08 11:38

import apps.course.utils
import django.core.validators
import django.db.models.deletion
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('icon', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('icon', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='levels', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('lang_code', models.CharField(max_length=3, verbose_name='Language')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discounted')),
                ('is_free', models.BooleanField(default=False, verbose_name='Is Free')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('discounted_expire_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='course.coursecategory', verbose_name='Discounted')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Level', to='course.courselevel', verbose_name='level')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending'), ('complaint', 'complaint')], max_length=50, verbose_name='Status')),
                ('comment_text', models.TextField(verbose_name='Comment Text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course comment',
                'verbose_name_plural': 'Course comments',
            },
        ),
        migrations.CreateModel(
            name='CurseCommentComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('complaint_type', models.CharField(blank=True, choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending'), ('complaint', 'complaint')], max_length=50, null=True, verbose_name='Complaint Type')),
                ('complaint_text', models.TextField(verbose_name='Complaint Text')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='course.coursecomment', verbose_name='Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursecommentcomplaint_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'CourseComment Complaint',
                'verbose_name_plural': 'CourseComment Complaints',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='course.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User course',
                'verbose_name_plural': 'User courses',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('payment_type', models.CharField(choices=[('uzcard', 'payme'), ('click', 'click'), ('paylov', 'paylov'), ('uzum bank', 'uzum bank')], max_length=50, verbose_name='Payment type')),
                ('payment_status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], max_length=50, verbose_name='Payment status')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment date')),
                ('usercourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='course.usercourse', verbose_name='User Course')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body_text', models.CharField(max_length=255, verbose_name='Body Text')),
                ('video_path', models.FileField(upload_to='videos', verbose_name='Video Path')),
                ('video_duration', models.DurationField(blank=True, null=True, verbose_name='Video Duration')),
                ('video_thumbnail', models.ImageField(upload_to='thumbnails', verbose_name='Video thumbnail')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='course.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='VideoUserView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('last_watched_time', models.DurationField(blank=True, null=True, verbose_name='Last Watched Time')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('progress', models.IntegerField(blank=True, null=True, verbose_name='Progress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video_view', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video_view', to='course.videolesson', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'VideoUserView',
                'verbose_name_plural': 'VideoUserViews',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='Full Name')),
                ('cid', models.CharField(default=apps.course.utils.randomize_certificate_number, max_length=255, verbose_name='CID')),
                ('file', models.FileField(null=True, upload_to='certificates', verbose_name='File')),
                ('image', models.ImageField(null=True, upload_to='certificates', verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='FavouriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_courses', to='course.course', verbose_name='Favourite Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_courses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favourite Course',
                'verbose_name_plural': 'Favourite Courses',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
