# Generated by Django 5.0.1 on 2024-02-03 10:26

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/profile_pics/%Y/%m/%d/'),
        ),
    ]
